### PR TITLE
CoffeeScript -> JS

### PR DESCRIPTION
**Pull request by TimvdLippe**
This PR updates all coffeescript files to JS ES6 to be compatible with Hubot 3.

### CODE REVIEW

**Comment by patsissons** [comment]
submitted to the wrong repo?

**Comment by TimvdLippe** [comment]
Hm, no it was as intended. We are relying on `hubot-giphy` downstream, but it is incompatible with the latest version of Hubot (3). This PR is intended to make this package work on Hubot 3.

**Comment by patsissons** [comment]
ah sorry, i didn't realize this repo is what is published to npm.

**Comment by patsissons** [comment]
it looks like the coffeescript linter is still being applied, you probably want to get rid of that too

**Comment by TimvdLippe** [comment]
Should I remove all coffeescript related build tooling and replace it with
the equivalent for ES? Can do that tomorrow when I have my laptop again.

Op ma 4 dec. 2017 om 19:07 schreef Pat Sissons <notifications@github.com>:

**Comment by patsissons** [comment]
yea go ahead.

**Comment by TimvdLippe** [comment]
So that took a lot of figuring out, but eventually I got there. @patsissons check it out :smile:

**Comment by TimvdLippe** [comment]
@patsissons What would the path forward to get this change merged in? I think we should remove Node 0.12 from Travis?

**Comment by patsissons** [comment]
yea feel free to remove the old legacy node build, most of the files in this repo were templates off of some hubot template repo (or it may have been a yeoman template, i forget which one). Probably no sense in supporting 0.12 any more.

it looks like istanbul ignores are [not working properly](https://coveralls.io/builds/14507173/source?filename=src%2Fgiphy.js) either.

**Comment by patsissons** [comment]
istanbul [may require](https://github.com/gotwarlost/istanbul/blob/master/ignoring-code-for-coverage.md) `/* istanbul ignore if */` instead of just ignore next.

**Comment by TimvdLippe** [comment]
I got to sleep now. Tomorrow I will address these issues. Should be quite straightforward to fix 🎉

**Comment by TimvdLippe** [comment]
@patsissons Fixed :tada:

**Comment by TimvdLippe** [comment]
@patsissons awesome thanks for merging. Could you publish a new version of this package to NPM? Then I can depend on it in our downstream project :smile:

**Comment by patsissons** [comment]
I tried to do an RC publish yesterday, but I think my api key has gone stale. I'll try and create a new publish api key tonight so i can get travis to publish the module.

**Comment by patsissons** [comment]
ok, `0.7.0-rc.2` is now published. give it a shot and if all is good i can publish a non-beta.

**Pull request merged**
